### ISSUE TITLE
It always listens on 127.0.... and not on the node's IP when deploying to an external.

### ISSUE THREAD

**Issue by moula** [canonical/opensearch-dashboards-operator#121]
Hi, 
Opensearch-dashboard Listen on 127.0. and not on the fixed ip of the node opensearch-dashboard.
Despite the change to the /etc/hosts file.
Thank's. 

![Capture d’écran du 2024-10-01 13-06-05](https://github.com/user-attachments/assets/63c0f60f-bc2c-4284-bbda-6bc4ec822c54)

![Capture d’écran du 2024-10-01 13-16-16](https://github.com/user-attachments/assets/6bddc15e-948e-4f30-8eb3-c7b155134638)

**Comment by phvalguima** [comment]
Hi @moula thanks for the report! Indeed, I can confirm there is an issue when we have the `/etc/hosts` as you mentioned. I am working on a fix to move away from `socket` to `juju spaces` so we can fix this problem.
