### ISSUE TITLE
[BUG] Kibanaserver user used to authenticate to UI of dashboards

### ISSUE THREAD

**Issue by Mehdi-Bendriss** [canonical/opensearch-dashboards-operator#38]
The `kibanaserver` user is an **internal user** that is exceptionally exposed to the dashboards upon relating with OpenSearch. 

The Authentication on the UI is however **made** to happen through the `kibanaserver` user as opposed to the default `admin` user.

**Comment by juditnovak** [comment]
Does it mean that the local configuration of the Dashboards has to use the `admin` credentials instead?

OR that it's the admin user that should be passed through the relation and used by the Dashboard?

**Comment by juditnovak** [comment]
We (@phvalguima and myself) couldn't reproduce the issue, and found the Dashboards with full expected functionality.

Could you please add more details to the problem description? (We were both a bit confused about it.)

**Comment by Mehdi-Bendriss** [comment]
This is no longer relevant, authentication should be done through credentials provided by the data-integrator.
